---
title: "Explore scRNA-seq"
format: html
editor_options: 
  chunk_output_type: console
---

```{bash}
curl -O https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.1/src/hdf5-1.10.1.tar
tar -xf hdf5-1.10.1.tar
cd hdf5-1.10.1
./configure
make -j4
make check
make install

```


```{r}
devtools::install_github("aertslab/SCopeLoomR")
```


```{r}
library(tidyverse)
library(SCopeLoomR)
library(qs)
library(skimr)

```

```{r}
loom_path <- "~/Downloads/s_fca_biohub_glial_cell_10x.loom"
loom <- open_loom(loom_path, mode = "r+")
loom

dgem <- get_dgem(loom)
dgem[1:5,1:5]
dgem

```

```{r}
cell_anno <- get_cell_annotation(loom) %>%
  rownames_to_column(var = "cell_id")

cell_anno$annotation %>% unique() 
cell_anno$annotation_gt_10 %>% unique()
cell_anno$annotation_in_broad %>% unique()
cell_anno$annotation_in_broad_extrapolated %>% unique()
cell_anno$broad_annotation %>% unique()
cell_anno$broad_annotation_extrapolated %>% unique()

##
dgem_tibble <- dgem %>%
  as.data.frame() %>%
  rownames_to_column(var = "gene_name")

dgem_tidy <- dgem_tibble %>%
  pivot_longer(-gene_name, 
               names_to = "cell_id",
               values_to = "dgem")

dgem_tidy %>%
  arrange(desc(dgem)) %>%
  pull(gene_name) %>% unique() %>% head()

## 
spg_ids <- cell_anno %>%
  filter(broad_annotation_extrapolated == "glial cell") %>%
  filter(annotation == "subperineurial glial cell") %>%
  pull(cell_id) 

spg_dgem <- dgem_tibble %>%
  dplyr::select(gene_name, spg_ids)

spg_dgem_tidy <- spg_dgem %>%
  pivot_longer(-gene_name, 
               names_to = "cell_id",
               values_to = "dgem")

spg_dgem_tidy %>%
  filter(gene_name == "Mdr65") %>%
  ggplot(aes(x = dgem)) + 
  geom_histogram() +
  scale_y_log10() 

```






















