---
title: "TDP-43"
format: html
editor_options: 
  chunk_output_type: console
---

## Explore TDP-43 mislocalisation dataset

```{r}
library(tidyverse)
library(patchwork)
library(ggrepel)
library(qs)

tdp43_misloc <- read_tsv("./data/TDP-43/TDP43mislocalization.dm6.txt")
# fractionation <- read_tsv("./data/TDP-43/FractionationLR_z.txt")

colours <- c("gray70", "darkorange")
tdp43_misloc %>%
  ggplot(
    aes(x = log2FC_LR_final, y = -log10(pvalue.adjust), colour = CLIPin3UTR)
    ) +
  geom_hline(yintercept = -log10(0.05), colour = "gray70", linetype = "dashed") +
  geom_point(alpha = 0.8, stroke = 0, size = 1.75) +
  scale_colour_manual(values = colours) + 
  theme_minimal() -> p1

p1

tdp43_misloc %>%
  filter(pvalue.adjust < 0.05) %>%
  ggplot(
    aes(x = CLIPin3UTR, y = log2FC_LR_final, colour = CLIPin3UTR)
    ) +
  geom_boxplot() + 
  coord_flip() + 
  scale_colour_manual(values = colours) + 
  theme_minimal() +
  theme(legend.position = "none") -> p2 

p2 

p1/p2 + plot_layout(heights = c(10, 1))

```

## Attach Dmel Mmus DIOPT information (diopt_score >= 8)

```{r}
diopt_mousetofly <- qread("./data/DIOPT/mouse96-to-fly/DIOPT_mouse-to-fly.qs")
diopt_mousetofly_over8 <- diopt_mousetofly %>%
  filter(diopt_score >= 8)
tdp43_misloc$ensembl_gene_id %in% DIOPT_mmus_dmel$mmus_gene_id %>% skimr::skim()

# too_many_matches <- diopt_mousetofly %>%
#   filter(diopt_score >= 8) %>%
#   group_by(dmel_gene_id) %>%
#   slice_max(diopt_score, n = 3) %>% 
#   summarise(count = n()) %>% 
#   ungroup() %>%
#   filter(count >= 2) %>% pull(dmel_gene_id) 
# 
# diopt_conversion_table <- diopt_mousetofly %>%
#   filter(diopt_score >= 8) %>%
#   group_by(dmel_gene_id) %>%
#   slice_max(diopt_score, n = 3) %>%
#   ungroup() %>%
#   filter(if_else(
#     dmel_gene_id %in% too_many_matches, 
#     diopt_score >= 10,
#     diopt_score >= 8))

tdp43_misloc_dmel <- tdp43_misloc %>%
  left_join(diopt_mousetofly_over8, by = c("ensembl_gene_id" = "mmus_gene_id")) %>%
  distinct()

tdp43_misloc_dmel_summary <- tdp43_misloc_dmel %>%
  group_by(ensembl_gene_id) %>%
  summarise(
    MT_conversion = paste0(unique(flygenename), collapse = ", "),
    DIOPT_conversion = paste0(unique(dmel_gene_name), collapse = ", ")
    ) %>%
  mutate(across(contains("_conversion"), ~if_else(.x == "NA", NA, .x)))

skimr::skim(tdp43_misloc_dmel_summary)

tdp43_dmel_df <- tdp43_misloc_dmel %>%
  dplyr::select("mmus_gene_id" = ensembl_gene_id, Gene, dmel_gene_id, dmel_gene_name, diopt_score, log2FC_LR_final, pvalue.adjust, CLIPin3UTR) %>%
  distinct()

```

## Attach TDP-43 information into mata-analysis dataframe

```{r}
tdp43_dmel_df %>%
  group_by(dmel_gene_id) %>%
  summarise(n = n()) %>%
  mutate(n = as.factor(n)) %>%
  arrange(desc(n)) %>% skimr::skim(
  )

tdp43_dmel_df$dmel_gene_id %>% unique() %>% length()

tdp43_dmel_df_summary <- tdp43_dmel_df %>%
  group_by(dmel_gene_id) %>%
  summarise(
    mean_TDP43_KO_LR_l2fc = mean(log2FC_LR_final),
    median_TDP43_KO_LR_l2fc = median(log2FC_LR_final),
    min_TDP43_KO_LR_l2fc = min(log2FC_LR_final),
    max_TDP43_KO_LR_l2fc = max(log2FC_LR_final),
    mean_TDP43_KO_LR_padj = mean(pvalue.adjust),
    median_TDP43_KO_LR_padj = median(pvalue.adjust),
    min_TDP43_KO_LR_padj = min(pvalue.adjust),
    max_TDP43_KO_LR_padj = max(pvalue.adjust),
    TDP43_CLIPin3UTR_conversion = paste0(unique(CLIPin3UTR), collapse = ";"),
    TDP43_dataset_gene_ids = paste0(unique(mmus_gene_id), collapse = ";"),
    TDP43_dataset_gene_names = paste0(unique(Gene), collapse = ";")
  ) %>%
  mutate(TDP43_CLIPin3UTR = if_else(str_detect(TDP43_CLIPin3UTR_conversion, "yes"), "yes", "no"))

## Gala dataframe
gl_nd <- qread("./output/glia-localised-neurodegenerative-disease-incorporated.qs")

## 1700 genes
present_1700_genes <- gl_nd %>%
  filter(rna_in_protrusion >= 8) %>%
  filter(`subperineurial glial cell` == TRUE | 
           `perineurial glial sheath` == TRUE |
           `adult brain perineurial glial cell` == TRUE |
           `ensheathing glial cell` == TRUE) %>%
  pull(dmel_gene_id)

enriched_301_genes <- gl_nd %>%
  filter(enriched_in_protrusion >= 3) %>% 
  pull(dmel_gene_id)

## left join
gl_tdp <- gl_nd %>%
  mutate(present_1700_genes = if_else(dmel_gene_id %in% present_1700_genes, TRUE, FALSE)) %>%
  mutate(enriched_301_genes = if_else(dmel_gene_id %in% enriched_301_genes, TRUE, FALSE)) %>%
  left_join(tdp43_dmel_df_summary, by = "dmel_gene_id") 

## 
colours <- c("gray60", "coral")
plot_volcano_box <- function(fc, padj, var, colour_vec = colours){
  gl_tdp %>%
    mutate(label_volcano = if_else(
      abs(get({{fc}})) >= 0.9 & get({{padj}}) < 0.05,
      dmel_gene_name,
      NA_character_
    )) %>%
    ggplot(
      aes(x = get({{fc}}), y = -log10(get({{padj}})), colour = get({{var}}), label = label_volcano)
    ) + 
    geom_hline(yintercept = -log10(0.05), colour = "gray70", linetype = "dashed") +
    geom_vline(xintercept = 0, colour = "gray70", linetype = "dashed") +
    geom_point(alpha = 0.8, stroke = 0, size = 2) +
    geom_text_repel(colour = "black", cex = 2.5, max.overlaps = 50) + 
    labs(
      title = paste0("Taliaferro TDP-43 KO & \"Glia ", str_replace_all(var, "_", " "), "\""),
      x = str_replace_all(fc, "_", " "),
      y = str_replace_all(padj, "_", " "),
      colour = str_replace_all(var, "_", " "),
    ) +
    scale_colour_manual(values = colour_vec) +
    theme_classic() +
    theme(plot.title = element_text(hjust = 0.5, face = "bold")) + 
    annotate(geom = "text", x = 0.25, y = 180, label = "-> More enriched\n    in TDP-43 KO", hjust = 0, size = 3) +
    annotate(geom = "text", x = -0.25, y = 180, label = "  More enriched <-\nin TDP-43 WT", hjust = 1, size = 3) -> p1
  
  gl_tdp %>%
    filter(get({{padj}}) < 0.05) %>%
    ggplot(
      aes(x = get({{var}}), y = get({{fc}}), colour = get({{var}}))
    ) +
    geom_boxplot() + 
    geom_hline(yintercept = 0, colour = "gray70", linetype = "dashed") +
    
    coord_flip() + 
    labs(
      x = str_replace_all(var, "_", " "),
      y = str_replace_all(fc, "_", " ")
    ) +
    scale_colour_manual(values = colour_vec) + 
    theme_classic() +
    theme(legend.position = "none") -> p2
  
  p1/p2 + plot_layout(heights = c(10, 2))
}

plot_volcano_box("mean_TDP43_KO_LR_l2fc", "min_TDP43_KO_LR_padj", "present_1700_genes", colours)
ggsave("~/Desktop/TDP43KO-localisation_1700-present_genes.pdf", width = 8.5, height = 7.5)

plot_volcano_box("mean_TDP43_KO_LR_l2fc", "min_TDP43_KO_LR_padj", "enriched_301_genes", colour_vec = c("gray60", "violetred"))
ggsave("~/Desktop/TDP43KO-localisation_301-enriched_genes.pdf", width = 8.5, height = 7.5)




```














